<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_29.50_fa fa-trash-o fa-fw</name>
   <tag></tag>
   <elementGuidId>228b3758-bc60-4497-bf9c-0c9d9d2c6bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='cart']/div/div/table/tbody/tr[2]/td[7]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-trash-o.fa-fw</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c1e0e533-796c-4398-b5f8-b400ac118a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash-o fa-fw</value>
      <webElementGuid>8a747d09-670f-4a7f-926a-044cb713b60e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart&quot;)/div[@class=&quot;contentpanel&quot;]/div[@class=&quot;container-fluid cart-info product-list&quot;]/table[@class=&quot;table table-striped table-bordered&quot;]/tbody[1]/tr[2]/td[@class=&quot;align_center&quot;]/a[@class=&quot;btn btn-sm btn-default&quot;]/i[@class=&quot;fa fa-trash-o fa-fw&quot;]</value>
      <webElementGuid>a429722f-cada-4ee1-bbb2-836b1903b534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='cart']/div/div/table/tbody/tr[2]/td[7]/a/i</value>
      <webElementGuid>ea2e9338-0474-4628-8e93-27e20070346b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/a/i</value>
      <webElementGuid>b39fc137-818f-419f-a485-de3c0a79028f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
