<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- ArianaBejaBen _15aa10</name>
   <tag></tag>
   <elementGuidId>7e74c951-bd61-407c-bc14-6a226c54f7f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AccountFrm_zone_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountFrm_zone_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1fe6deea-2c4a-47b9-9eb2-c5ed6367c4d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>ee70f972-f6c0-4b5c-a5ba-0109624c8b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountFrm_zone_id</value>
      <webElementGuid>3c9aea8c-00e6-4391-9d3a-ab4981a70967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>1ebac7ec-9227-4b26-828b-c365e9699c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- ArianaBejaBen ArousBizerteGabesGafsaJendoubaKairouanKasserineKebiliKefMahdiaManoubaMedenineMonastirNabeulSfaxSidiSilianaSousseTataouineTozeurTunisZaghouan</value>
      <webElementGuid>9f6965b8-4b43-4cde-9a66-931c9ef536e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountFrm_zone_id&quot;)</value>
      <webElementGuid>39b97285-d9b8-4c69-90dd-40e6470b2bbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AccountFrm_zone_id']</value>
      <webElementGuid>9417f228-aad6-4dce-b18e-8cb64ed2439a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AccountFrm']/div[2]/fieldset/div[5]/div/select</value>
      <webElementGuid>c68c4e35-e9d3-4429-b914-fcd2b9763482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State:'])[1]/following::select[1]</value>
      <webElementGuid>c793dd0d-75f9-4100-be65-0eae323a3aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>fc538c5b-b3f4-4449-8f6d-015c9644f5eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>1c117702-7a3e-42e1-a2ca-f3609020c3c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code:'])[1]/preceding::select[1]</value>
      <webElementGuid>71037e06-2ad0-464c-a055-0ffbf889419d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>2d782298-bc9f-42d8-92ab-c49a763a70a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'AccountFrm_zone_id' and (text() = ' --- Please Select --- ArianaBejaBen ArousBizerteGabesGafsaJendoubaKairouanKasserineKebiliKefMahdiaManoubaMedenineMonastirNabeulSfaxSidiSilianaSousseTataouineTozeurTunisZaghouan' or . = ' --- Please Select --- ArianaBejaBen ArousBizerteGabesGafsaJendoubaKairouanKasserineKebiliKefMahdiaManoubaMedenineMonastirNabeulSfaxSidiSilianaSousseTataouineTozeurTunisZaghouan')]</value>
      <webElementGuid>669eb4de-a636-4702-844c-1c1a1fcbae99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select a region / state!'])[1]/preceding::select[1]</value>
      <webElementGuid>4a92257c-57a0-454f-85d8-25227a946569</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
