<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--- Please Select --- AberdeenAberde_0b0437</name>
   <tag></tag>
   <elementGuidId>13d82a91-c589-48d2-b0bc-cc1d558cd634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AccountFrm_zone_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountFrm_zone_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3495fa70-d514-4853-944d-c4b733f09f01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zone_id</value>
      <webElementGuid>ec8b9e1a-ea6c-460e-a50b-74f121d2a521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountFrm_zone_id</value>
      <webElementGuid>1009338f-d7e7-4cca-864f-4f3c4c22eb8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control </value>
      <webElementGuid>83178ef8-09da-4dfc-929b-b81cc949dc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham</value>
      <webElementGuid>9f315daf-cba9-4e16-a91e-4a47be098dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountFrm_zone_id&quot;)</value>
      <webElementGuid>ec443ee6-184b-4506-8be9-395cf1aa57fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AccountFrm_zone_id']</value>
      <webElementGuid>0eaaa6e1-65fd-4103-a254-5794f9a6cad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='AccountFrm']/div[2]/fieldset/div[5]/div/select</value>
      <webElementGuid>dcec7658-4697-4d55-8387-c6c30428674d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region / State:'])[1]/following::select[1]</value>
      <webElementGuid>425cd747-81d7-47f6-9676-03879fa3172e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>a0bb7fb7-2fc4-4607-a6ec-f96d379ca9aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>9463c420-ddb3-49b2-9fa5-833689d2aa1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZIP Code:'])[1]/preceding::select[1]</value>
      <webElementGuid>9450192d-50ae-431c-a09c-8113ba98e798</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>42dd59b9-f926-4274-8a62-eb8250a6d5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'zone_id' and @id = 'AccountFrm_zone_id' and (text() = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham' or . = ' --- Please Select --- AberdeenAberdeenshireAngleseyAngusArgyll and ButeBedfordshireBerkshireBlaenau GwentBridgendBristolBuckinghamshireCaerphillyCambridgeshireCardiffCarmarthenshireCeredigionCheshireClackmannanshireConwyCornwallDenbighshireDerbyshireDevonDorsetDumfries and GallowayDundeeDurhamEast AyrshireEast DunbartonshireEast LothianEast RenfrewshireEast Riding of YorkshireEast SussexEdinburghEssexFalkirkFifeFlintshireGlasgowGloucestershireGreater LondonGreater ManchesterGwyneddHampshireHerefordshireHertfordshireHighlandsInverclydeIsle of WightKentLancashireLeicestershireLincolnshireMerseysideMerthyr TydfilMidlothianMonmouthshireMorayNeath Port TalbotNewportNorfolkNorth AyrshireNorth LanarkshireNorth YorkshireNorthamptonshireNorthumberlandNottinghamshireOrkney IslandsOxfordshirePembrokeshirePerth and KinrossPowysRenfrewshireRhondda Cynon TaffRutlandScottish BordersShetland IslandsShropshireSomersetSouth AyrshireSouth LanarkshireSouth YorkshireStaffordshireStirlingSuffolkSurreySwanseaTorfaenTyne and WearVale of GlamorganWarwickshireWest DunbartonshireWest LothianWest MidlandsWest SussexWest YorkshireWestern IslesWiltshireWorcestershireWrexham')]</value>
      <webElementGuid>05ed463f-e2f7-432e-a64e-2384b170b7c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
