<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Linkedin</name>
   <tag></tag>
   <elementGuidId>63a841f1-1ab9-451f-a992-9c9987b4bfbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.linkedin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Linkedin')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Linkedin&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b6831b46-8123-442c-ae1c-69faa5c3d2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://uk.linkedin.com/</value>
      <webElementGuid>a87be6ba-acef-4130-bdad-fb3298d9d9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Linkedin</value>
      <webElementGuid>4e98e305-ea83-4ffc-8dc5-4d04702f8554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>linkedin</value>
      <webElementGuid>61b8f4ce-954b-4d59-8bdd-d60690dd6cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Linkedin</value>
      <webElementGuid>5267e232-464d-40ab-85fb-c9bb691741db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/div[@class=&quot;container-fixed&quot;]/header[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 headerdetails&quot;]/div[@class=&quot;block_8&quot;]/div[@class=&quot;header_block&quot;]/div[@class=&quot;social_icons&quot;]/a[@class=&quot;linkedin&quot;]</value>
      <webElementGuid>6402a05d-3475-4787-b0b1-3d9eb795b3e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Linkedin')]</value>
      <webElementGuid>4b847fae-e5cd-48cc-8f6f-98553366f272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Twitter'])[1]/following::a[1]</value>
      <webElementGuid>f09350f5-1632-47c6-97ef-1ca6a2a64908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::a[2]</value>
      <webElementGuid>dfd59620-7323-498c-a331-e8256d11d2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[1]</value>
      <webElementGuid>b010da69-8471-48a3-b80e-56eb6b9eb60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Specials'])[2]/preceding::a[2]</value>
      <webElementGuid>26252d08-9626-4d91-b3bd-9db366cb90e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Linkedin']/parent::*</value>
      <webElementGuid>8e2db739-a422-4120-a3d7-903bf8d3c9e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://uk.linkedin.com/')]</value>
      <webElementGuid>13f8f485-8078-442d-b8b1-2a22e709286a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>c5674357-54fe-4865-bbdc-77ee986727cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://uk.linkedin.com/' and @title = 'Linkedin' and (text() = 'Linkedin' or . = 'Linkedin')]</value>
      <webElementGuid>959c95ff-05e2-491b-bf7c-b8a53791c3a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
