<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Shipping</name>
   <tag></tag>
   <elementGuidId>8a75e979-c891-4ec5-94c3-538526ef3e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='footer']/footer/section[2]/div/div/div/ul/li[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.open > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1edc93a7-6306-4ad1-a227-ca6bda0301c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://automationteststore.com/index.php?rt=content/content&amp;content_id=4</value>
      <webElementGuid>d417e5d1-ecb7-4a43-a9a1-0e7906fd9ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipping</value>
      <webElementGuid>325a300f-370e-4bc9-a75a-8e4481f16365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer&quot;)/footer[1]/section[@class=&quot;footerlinks&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;pull-left&quot;]/div[@class=&quot;info&quot;]/ul[@class=&quot;info_links_footer&quot;]/li[4]/div[@class=&quot;dropdown open&quot;]/a[1]</value>
      <webElementGuid>40e5eb40-7035-4324-a0af-426be8677a2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer']/footer/section[2]/div/div/div/ul/li[4]/div/a</value>
      <webElementGuid>9c38481e-e12d-44ce-b5eb-5af5c916617c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shipping')]</value>
      <webElementGuid>012d9039-f2a4-428f-ac2b-d2ef1ad8076f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Return Policy'])[1]/following::a[1]</value>
      <webElementGuid>3887719e-55b0-439e-874f-d9be81ee0f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/following::a[2]</value>
      <webElementGuid>35bd5240-3568-460b-968d-c11a4b5eb556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/preceding::a[1]</value>
      <webElementGuid>9ff17836-4da6-4ac6-b33c-5346bd6eca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site Map'])[1]/preceding::a[2]</value>
      <webElementGuid>13fbb7da-21d8-4b52-9249-1664325afdb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipping']/parent::*</value>
      <webElementGuid>3c52e272-18fa-4af9-9f92-8975a17a8535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://automationteststore.com/index.php?rt=content/content&amp;content_id=4')]</value>
      <webElementGuid>d67a44dc-3071-477f-aabb-89171cbef3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/div/div/ul/li[4]/div/a</value>
      <webElementGuid>f8ba586e-b3c4-4a6f-9f31-f74fadce53dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://automationteststore.com/index.php?rt=content/content&amp;content_id=4' and (text() = 'Shipping' or . = 'Shipping')]</value>
      <webElementGuid>dd7ae8ec-742b-44ab-bbf2-3f82cdd2c1bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
