<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Twitter</name>
   <tag></tag>
   <elementGuidId>dc14d1d5-5af9-46ff-9a7e-d6682c551512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.twitter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Twitter')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=banner >> internal:role=link[name=&quot;Twitter&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d535c5fd-e67a-4159-b31a-c09203a50256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://twitter.com/</value>
      <webElementGuid>a87bbc74-8394-4367-8f8e-30f0742b2ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>951e040c-72dd-4ab0-a0be-cdf1fca7a57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>edd2224e-490f-4043-be31-40af9a56384c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>twitter</value>
      <webElementGuid>f5e2dfe4-9925-4106-82a1-c81f094d9f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener</value>
      <webElementGuid>15d05f29-d9d5-46f9-a5e9-b8d03bec49eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Twitter</value>
      <webElementGuid>6a83f81b-b95b-457f-9698-62688aeb555c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;home&quot;]/div[@class=&quot;container-fixed&quot;]/header[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;col-md-12 headerdetails&quot;]/div[@class=&quot;block_8&quot;]/div[@class=&quot;header_block&quot;]/div[@class=&quot;social_icons&quot;]/a[@class=&quot;twitter&quot;]</value>
      <webElementGuid>dcb3e149-9dfa-40f2-9be3-9107a62a0021</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Twitter')]</value>
      <webElementGuid>50e068e3-b212-479b-b216-c9b3ae39cc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook'])[1]/following::a[1]</value>
      <webElementGuid>02699d85-9a6c-4068-9130-3efe76e9fb27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[4]</value>
      <webElementGuid>4fa4bafb-8c41-4aed-8cb9-e38836815d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Linkedin'])[1]/preceding::a[1]</value>
      <webElementGuid>19948360-2782-4b5e-a78f-0bd7ae414d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[2]</value>
      <webElementGuid>0130e6a8-8666-4933-b1e2-0832ae0af16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Twitter']/parent::*</value>
      <webElementGuid>8e5e7c8a-445f-4920-a880-46455f4fef29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://twitter.com/')]</value>
      <webElementGuid>f123f15c-1c4c-461e-af03-c871ee94aadb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>5cd916f9-8633-4faa-946e-ec8f3ba1f594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://twitter.com/' and @title = 'Twitter' and (text() = 'Twitter' or . = 'Twitter')]</value>
      <webElementGuid>e168dcf2-0ebd-4b8b-8604-0cc110011c4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
