<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brands Scrolling List_internal_1_2_3</name>
   <tag></tag>
   <elementGuidId>9f3d79a9-868f-4ae3-8d3d-0d66b24e73c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='brandcarousal']/li[4]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > div.image > a > img.internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Lancôme&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0ac9ec4a-6cbe-41a9-9e04-40e3938ce982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>6d8bab60-11f5-4766-9e05-f33801837128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//automationteststore.com/image/thumbnails/18/71/mf_lancome_logo_gif-100119-56x56.gif</value>
      <webElementGuid>2a4d6054-0b21-4628-a9a4-d062974af1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>96b5cfc8-bbb8-41cf-aa8b-26a4abbd4ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>d84d8ee0-e9f7-463d-b870-a315e1036af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Lancôme</value>
      <webElementGuid>6e4985ba-5187-4acd-9473-de1388192cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandcarousal&quot;)/li[4]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;internal&quot;]</value>
      <webElementGuid>098c8454-6cc4-45d6-8cde-3c904465cd0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='brandcarousal']/li[4]/div/a/img</value>
      <webElementGuid>85d6fae4-38d8-4942-83d6-78300ccb7c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Lancôme']</value>
      <webElementGuid>e06b878f-fb62-438b-9b1d-6295a0e1696a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/a/img</value>
      <webElementGuid>0e8ce1c3-3c8b-4855-944b-01e234fd3baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//automationteststore.com/image/thumbnails/18/71/mf_lancome_logo_gif-100119-56x56.gif' and @alt = 'Lancôme']</value>
      <webElementGuid>b20705b9-5c19-4faa-9ff4-9f4f5461fffb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
