<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brands Scrolling List_internal_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>26223b7d-3870-4da5-8b2d-2dd8f4937d2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='brandcarousal']/li[8]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(8) > div.image > a > img.internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Calvin Klein&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1f40cc9d-302d-4f6e-bc44-3aec4f34235c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>e2dd0807-a3b5-4c9e-ba5b-c8a082cd8f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//automationteststore.com/image/thumbnails/18/71/mf_calvin_klein_jpg-100116-56x56.jpg</value>
      <webElementGuid>314a0bc7-380e-427a-85f5-b092bc959a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>eee85af6-3663-47e6-82d2-9ec0df7601cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>70b201e3-91ee-4e0b-a076-8de241f9089d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Calvin Klein</value>
      <webElementGuid>eedd789f-756b-4188-8258-1478caa7c8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandcarousal&quot;)/li[8]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;internal&quot;]</value>
      <webElementGuid>735a38b1-cf2b-4944-aade-54d20c79532d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='brandcarousal']/li[8]/div/a/img</value>
      <webElementGuid>196cdca1-82c6-4091-8e32-0f3539186757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Calvin Klein']</value>
      <webElementGuid>0ebc01b4-080b-42ad-a875-83417e437e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/a/img</value>
      <webElementGuid>641e19cd-7b3b-4876-9229-4c9b589a5b35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//automationteststore.com/image/thumbnails/18/71/mf_calvin_klein_jpg-100116-56x56.jpg' and @alt = 'Calvin Klein']</value>
      <webElementGuid>1954c199-d32d-4c55-aa45-7d6dfcdc8dd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
