<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brands Scrolling List_internal_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>db936a40-c2c6-405d-8483-4414768f5a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='brandcarousal']/li[10]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(10) > div.image > a > img.internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Sephora&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>83dc395b-cec6-4799-8a1e-447f86077d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>9ea641af-f280-4665-ae26-d2a9d8952645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//automationteststore.com/image/thumbnails/18/71/mf_sephora_ba_logo_black_jpg-100114-56x56.jpg</value>
      <webElementGuid>90a95dc6-1a86-436d-ac2c-9034274e8dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>b78e6b8d-9ccb-45fa-93a0-036b34d48829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>7e74a0c2-d7e4-4d64-9857-98eabfebef06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sephora</value>
      <webElementGuid>2d78bf52-c610-406c-af22-460e9b4d0a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandcarousal&quot;)/li[10]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;internal&quot;]</value>
      <webElementGuid>c3635970-acf5-456f-8714-c33bfd15867c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='brandcarousal']/li[10]/div/a/img</value>
      <webElementGuid>16583933-7b90-48ad-b3db-e00837cde284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sephora']</value>
      <webElementGuid>6144bc7b-26cf-4273-b3e3-9f0f857e69db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/div/a/img</value>
      <webElementGuid>906b6091-b30f-4151-bf45-b1149e52a236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//automationteststore.com/image/thumbnails/18/71/mf_sephora_ba_logo_black_jpg-100114-56x56.jpg' and @alt = 'Sephora']</value>
      <webElementGuid>47b708a8-2ffb-41a5-8566-84a2f2aceec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
