<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brands Scrolling List_internal_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>f7abd922-0502-4f2d-aec7-8eb9521bc0bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='brandcarousal']/li[6]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > div.image > a > img.internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Giorgio Armani&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7da9d4c6-96e3-4921-a957-77343e087f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>936afa88-c9ac-432f-b7a4-0e8a7f0389aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//automationteststore.com/image/thumbnails/18/71/mf_armani_logo_gif-100122-56x56.gif</value>
      <webElementGuid>8f847198-4328-420d-bb0a-bf8016e1175b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>db54219e-b130-4446-a39f-a4d729d1109c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>57fa1cc8-a335-48eb-ad6c-7eba95348bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Giorgio Armani</value>
      <webElementGuid>ad855197-6e22-47e9-814e-b6616fc1b813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandcarousal&quot;)/li[6]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;internal&quot;]</value>
      <webElementGuid>8ea26e31-2daf-45a1-a1ad-480b1fedcb89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='brandcarousal']/li[6]/div/a/img</value>
      <webElementGuid>32a3f866-ead4-49e8-acf8-86266ab22c12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Giorgio Armani']</value>
      <webElementGuid>6af2f9bf-97ea-4b02-9794-ef8f913ab1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/div/a/img</value>
      <webElementGuid>036e0c42-e58c-4f2b-b848-76601683bd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//automationteststore.com/image/thumbnails/18/71/mf_armani_logo_gif-100122-56x56.gif' and @alt = 'Giorgio Armani']</value>
      <webElementGuid>f051366f-bb0e-45bf-8fae-89a74e6cafbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
