<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Brands Scrolling List_internal_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>9b57ad66-4522-48e7-9df7-4214acb26d1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='brandcarousal']/li[5]/div/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > div.image > a > img.internal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Gucci&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>270164ac-f60a-4a0b-a84d-db81abdc72ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>internal</value>
      <webElementGuid>ceddd307-9ddf-4bf1-9b8c-f22bdbfa5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//automationteststore.com/image/thumbnails/18/73/demo_mf_gucci_jpg-100153-56x56.jpg</value>
      <webElementGuid>02dcd807-5511-473a-ba56-0e71d5ea2e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>f286b7c3-0fdf-42e6-947f-a8bf9d45b219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>2cdc15c4-9292-4082-b49a-7560bea29587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Gucci</value>
      <webElementGuid>01209094-f69b-441c-9913-4c383557c950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandcarousal&quot;)/li[5]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;internal&quot;]</value>
      <webElementGuid>634beb2b-9af4-48dc-a29c-6e1ad5945ca0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='brandcarousal']/li[5]/div/a/img</value>
      <webElementGuid>6aca9c02-b6e1-47d6-b52b-ae3f40be259b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Gucci']</value>
      <webElementGuid>e5820692-123d-4a03-a795-b32c16f4bd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/a/img</value>
      <webElementGuid>bcfa5ea6-bee3-4469-9dc2-190433e0ee52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '//automationteststore.com/image/thumbnails/18/73/demo_mf_gucci_jpg-100153-56x56.jpg' and @alt = 'Gucci']</value>
      <webElementGuid>afa3ce75-fe3b-436b-84ce-4994c6c23bc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
